services:
  web:
    image: php:8.2-apache
    container_name: peace_seafood_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  composer:
    image: composer:2
    container_name: peace_seafood_composer
    volumes:
      - ./:/app

  db:
    image: mysql:8.0
    container_name: peace_seafood_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peace_seafood
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
