<?php

declare(strict_types=1);

/**
 * Role & Permission Definitions
 */

return [
    'super_admin' => [
        'dashboard.*',
        'stok.*',
        'penjualan.*',
        'penitipan.*',
        'retur.*',
        'keuangan.*',
        'laporan.*',
        'master_data.*',
        'harga.*',
        'settings.*',
        'user.*',
        'export.*',
        'notifikasi.*',
    ],
    'bos' => [
        'dashboard.view',
        'stok.view',
        'stok.history',
        'stok.create',
        'stok.timbang',
        'penjualan.view',
        'penjualan.create',
        'penitipan.view',
        'retur.view',
        'keuangan.view',
        'laporan.view',
        'laporan.export',
        'settings.view',
        'notifikasi.*',
    ],
    'admin' => [
        'dashboard.view',
        'stok.view',
        'stok.history',
        'stok.create',
        'stok.update',
        'stok.timbang',
        'penjualan.view',
        'penjualan.create',
        'penjualan.update',
        'penjualan.cancel',
        'penitipan.view',
        'penitipan.create',
        'penitipan.update',
        'retur.view',
        'retur.create',
        'retur.approve',
        'retur.reject',
        'keuangan.view',
        'keuangan.create',
        'keuangan.bayar',
        'laporan.view',
        'master_data.view',
        'master_data.*',
        'harga.*',
        'notifikasi.view',
        'notifikasi.read',
    ],
    'checker' => [
        'dashboard.view',
        'stok.view',
        'stok.timbang',
        'stok.create',
        'retur.view',
        'penjualan.create_draft',
        'notifikasi.view',
        'notifikasi.read',
    ],
    'saas_owner' => [
        'dashboard.view',
        'settings.*',
        'user.*',
        'export.*',
        'migrasi.*',
        'notifikasi.*',
        'master_data.view',
    ],
];
